name: Update Contribution Snake

on:
  schedule:
    - cron: "0 */12 * * *"    # every 12h
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate snake game
        uses: platane/snk@v3
        with:
          github_user_name: lrtsyl
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif
          github_token: ${{ secrets.GITHUB_TOKEN }}
          include_private: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
