name: Generate Snake Animation

on:
  schedule:
    - cron: '0 */12 * * *' # every 12 hours
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare dist folder
        run: |
          rm -rf dist && mkdir dist

      - name: Generate snake animation & SVG
        uses: Platane/snk@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif
          args: --include-private

      - name: Verify generated files
        run: |
          echo "→ dist contains:" && ls -l dist
          test -f dist/github-contribution-grid-snake.svg
          test -f dist/github-contribution-grid-snake.gif

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
